// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDYoqgPYi1uK3KhaIrmtwe19tRCPFElOk',
    appId: '1:205365347914:android:df1adf228a57145a01c8b3',
    messagingSenderId: '205365347914',
    projectId: 'teamflutter1-68d5b',
    storageBucket: 'teamflutter1-68d5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuLMX4bH_d6bpsAOFAtyWy9hdWAmQ6R0o',
    appId: '1:205365347914:ios:ce46901e9507d38701c8b3',
    messagingSenderId: '205365347914',
    projectId: 'teamflutter1-68d5b',
    storageBucket: 'teamflutter1-68d5b.firebasestorage.app',
    androidClientId: '205365347914-mh5s3ojj52p2rac4k510sriidetfc0n0.apps.googleusercontent.com',
    iosClientId: '205365347914-272t56ide90ne4pe4rsf32c1uatr5rch.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylishEcommerce',
  );
}
